---
title: "PHCM9795 Foundations of Biostatistics"
author: "Pilot Notes for R"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
documentclass: memoir
mainfont: Roboto
sansfont: Clancy
monofontoptions: 'Scale=0.9'
monofont: Roboto Mono
bibliography: [PHCM9795.bib]
link-citations: yes
---

# Introduction {.unnumbered}

These notes provide an introduction to R and instructions on how to conduct the analyses introduced in Foundations of Biostatistics.

These notes are currently under development, with sections being added and revised as the course progresses.

This is the first year that R has been offered as an option. I am keen to receive feedback about the notes and your experience learning R. Please [get in touch](mailto:t.dobbins@unsw.edu.au) if anything is unclear, or you have any questions or suggestions.

### Changelog {-}

**2022-06-07**

[Changed]

- Section 2.6: Use the `<-` operator instead of `=`

**2022-06-05**

[Changed]

- Module 1: Typos


**2022-05-30**

[Changed]

- Module 1: Typo in R Preferences (Section 1.3.1)

[Added]

- Section 1.12: Instructions to plot a histogram with relative frequencies (i.e. percents) instead of frequencies

**2022-05-27**

[Changed]

- Module 1: Fixed bar-charts that were not plotted correctly

**2022-05-27**

[Added]

-   Section 1.2.1: Added a note about using the "patched" version of R 4.2.0 for Windows
-   Section 1.14: Instructions for creating two-way tables using the `contTables()` function in the `jmv` package

**2022-05-23**

[Added]

-   Section 1.9: Explicit instructions to install `jmv` and `summarytools` when working in Module 1

[Changed]

-   Section 1.9: Changed location of `pbc.dat` from `examples` to `activities` folder for consistency

**2022-05-19**

Initial release
