# Sample size

Many power and sample size procedures are available in the `epiR` package.


```r
# If not yet installed, submit the following:
# install.packages("epiR")
library(epiR)
```

## Sample size calculation for two independent samples t-test
To do the problem discussed in Worked Example 10.2, we use the `epi.sscompc` function: **Sample size, power and minimum detectable difference when comparing continuous outcomes**.

```
epi.sscompc(treat, control, n, sigma, power, 
   r = 1, design = 1, sided.test = 2, nfractional = FALSE, conf.level = 0.95)
```

The first line contains parameters that we can specify, with one parameter that is to be calculated. That is, we define values for four of the five parameters, and the remaining parameter is calculated. For example, we can define the mean in the treated group, the mean in the control group, the assumed standard deviation and the desired power, and the function will calculate the required sample size. We specify the unknown value as being equal to R's missing value, `NA`.

For example, to calculate the required sample size in Worked Example 10.2, we specify:

- the assumed mean in the experimental, or treatment, group: 90mmHg
- the assumed mean in the control group: 95mmHg
- the standard deviation of blood pressure: 5mmHg
- the required power, 0.9 (representing 90%)

The values on the second line of the function are defined by default, and we can leave these as default.

Putting this all together, and specifying the sample size as unknown:


```r
epi.sscompc(treat=90, control=95, n=NA, sigma=5, power=0.9) 
#> $n.total
#> [1] 44
#> 
#> $n.treat
#> [1] 22
#> 
#> $n.control
#> [1] 22
#> 
#> $power
#> [1] 0.9
#> 
#> $delta
#> [1] 5
```

The results indicate that we need 22 participants in each group, or 44 in total.

We can define whether we want unequal numbers in each group by specifying `r`: the number in the treatment group divided by the number in the control group.

## Sample size calculation for difference between two independent proportions

To do the problem discussed in Worked Example 10.3, we use the `epi.sscohortc` function: **Sample size, power or minimum detectable incidence risk ratio for a cohort study using individual count data**.

```
epi.sscohortc(irexp1, irexp0, pexp = NA, n = NA, power = 0.80, 
   r = 1, N, design = 1, sided.test = 2, finite.correction = FALSE, 
   nfractional = FALSE, conf.level = 0.95)
```

We can enter:

- irexp1: the assumed risk of the outcome in the exposed group: here 0.35
- irexp0: the assumed risk of the outcome in the unexposed group: here 0.2
- n: the total sample size, to be determined
- power: the required power: here 0.8 (representing 80%)


```r
epi.sscohortc(irexp1=0.35, irexp0=0.2, n=NA, power=0.8) 
#> $n.total
#> [1] 276
#> 
#> $n.exp1
#> [1] 138
#> 
#> $n.exp0
#> [1] 138
#> 
#> $power
#> [1] 0.8
#> 
#> $irr
#> [1] 1.75
#> 
#> $or
#> [1] 2.153846
```

Note: It doesn’t matter if you swap the proportions for the **exposed** and **unexposed** groups, i.e. the command `epi.sscohortc(irexp1=0.2, irexp0=0.35, n=NA, power=0.8) ` gives the same results.

## Sample size calculation with a relative risk

The `epiR` package does not have a function to estimate sample size and power directly for a relative risk, but we can use the `epi.sscohortc` function.

## Sample size calculation with an odds ratio

We can use the `epi.sscc` function to calculate a sample size based on an odds ratio in a case-control study: 

```
epi.sscc(OR, p1 = NA, p0, n, power, r = 1, 
   phi.coef = 0, design = 1, sided.test = 2, nfractional = FALSE, 
   conf.level = 0.95, method = "unmatched", fleiss = FALSE)
```

Using information from Worked Example 10.4, we specify:

- OR: the odds ratio to be detected, here 1.5
- p0: the proportion of the outcome in the controls, here 0.5
- n: the sample size, here to be calculated
- power: the required study power, here 0.9


```r
epi.sscc(OR=1.5, p0=0.5, n=NA, power=0.9)
#> $n.total
#> [1] 1038
#> 
#> $n.case
#> [1] 519
#> 
#> $n.control
#> [1] 519
#> 
#> $power
#> [1] 0.9
#> 
#> $OR
#> [1] 1.5
```

Now we calculate the sample size for Worked Example 10.5:


```r
epi.sscc(OR=2, p0=0.3, n=NA, power=0.9)
#> $n.total
#> [1] 376
#> 
#> $n.case
#> [1] 188
#> 
#> $n.control
#> [1] 188
#> 
#> $power
#> [1] 0.9
#> 
#> $OR
#> [1] 2
```

Here we see that we require a total of 376 participants to detect an odds ratio of 2.0 with 90% power;


```r
epi.sscc(OR=2, p0=0.3, n=NA, power=0.8)
#> $n.total
#> [1] 282
#> 
#> $n.case
#> [1] 141
#> 
#> $n.control
#> [1] 141
#> 
#> $power
#> [1] 0.8
#> 
#> $OR
#> [1] 2
```

or a total of 282 participants to detect an odds ratio of 2.0 with 80% power.
