<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Module 1 Introduction to R and RStudio | PHCM9795 Foundations of Biostatistics</title>
  <meta name="description" content="Module 1 Introduction to R and RStudio | PHCM9795 Foundations of Biostatistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Module 1 Introduction to R and RStudio | PHCM9795 Foundations of Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Module 1 Introduction to R and RStudio | PHCM9795 Foundations of Biostatistics" />
  
  
  

<meta name="author" content="Pilot Notes for R" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="probability-and-probability-distributions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PHCM9795 Foundations of Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> Introduction to R and RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#learning-outcomes"><i class="fa fa-check"></i>Learning outcomes</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#part-1-an-introduction-to-r"><i class="fa fa-check"></i>Part 1: An introduction to R</a></li>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#r-vs-rstudio"><i class="fa fa-check"></i><b>1.1</b> R vs RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>1.2</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#recommended-setup"><i class="fa fa-check"></i><b>1.3</b> Recommended setup</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#simpleR"><i class="fa fa-check"></i><b>1.4</b> A simple R analysis</a></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#the-rstudio-environment"><i class="fa fa-check"></i><b>1.5</b> The RStudio environment</a></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#some-r-basics"><i class="fa fa-check"></i><b>1.6</b> Some R basics</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#what-is-this-thing-called-the-tidyverse"><i class="fa fa-check"></i><b>1.7</b> What is this thing called the tidyverse?</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#part-2-obtaining-basic-descriptive-statistics"><i class="fa fa-check"></i>Part 2: Obtaining basic descriptive statistics</a></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#set-up-your-data"><i class="fa fa-check"></i><b>1.8</b> Set up your data</a></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#reading-a-data-file"><i class="fa fa-check"></i><b>1.9</b> Reading a data file</a></li>
<li class="chapter" data-level="1.10" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#summarising-continuous-variables"><i class="fa fa-check"></i><b>1.10</b> Summarising continuous variables</a></li>
<li class="chapter" data-level="1.11" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#producing-a-histogram"><i class="fa fa-check"></i><b>1.11</b> Producing a histogram</a></li>
<li class="chapter" data-level="1.12" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#producing-a-boxplot"><i class="fa fa-check"></i><b>1.12</b> Producing a boxplot</a></li>
<li class="chapter" data-level="1.13" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#producing-a-one-way-frequency-table"><i class="fa fa-check"></i><b>1.13</b> Producing a one-way frequency table</a></li>
<li class="chapter" data-level="1.14" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#producing-a-two-way-frequency-table"><i class="fa fa-check"></i><b>1.14</b> Producing a two-way frequency table</a></li>
<li class="chapter" data-level="1.15" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#saving-data-in-r"><i class="fa fa-check"></i><b>1.15</b> Saving data in R</a></li>
<li class="chapter" data-level="1.16" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#copying-output-from-r"><i class="fa fa-check"></i><b>1.16</b> Copying output from R</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#part-3-creating-other-types-of-graphs"><i class="fa fa-check"></i>Part 3: Creating other types of graphs</a></li>
<li class="chapter" data-level="1.17" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#bar-graphs"><i class="fa fa-check"></i><b>1.17</b> Bar graphs</a></li>
<li class="chapter" data-level="1.18" data-path="introduction-to-r-and-rstudio.html"><a href="introduction-to-r-and-rstudio.html#creating-line-graphs"><i class="fa fa-check"></i><b>1.18</b> Creating line graphs</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html"><i class="fa fa-check"></i><b>2</b> Probability and probability distributions</a>
<ul>
<li class="chapter" data-level="2.1" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#importing-data-into-r"><i class="fa fa-check"></i><b>2.1</b> Importing data into R</a></li>
<li class="chapter" data-level="2.2" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#checking-your-data-for-errors-in-r"><i class="fa fa-check"></i><b>2.2</b> Checking your data for errors in R</a></li>
<li class="chapter" data-level="2.3" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#overlaying-a-normal-curve-on-a-histogram"><i class="fa fa-check"></i><b>2.3</b> Overlaying a Normal curve on a histogram</a></li>
<li class="chapter" data-level="2.4" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#descriptive-statistics-for-checking-normality"><i class="fa fa-check"></i><b>2.4</b> Descriptive statistics for checking normality</a></li>
<li class="chapter" data-level="2.5" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#import-excel"><i class="fa fa-check"></i><b>2.5</b> Importing Excel data into R</a></li>
<li class="chapter" data-level="2.6" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#generating-new-variables"><i class="fa fa-check"></i><b>2.6</b> Generating new variables</a></li>
<li class="chapter" data-level="2.7" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#summarising-data-by-another-variable"><i class="fa fa-check"></i><b>2.7</b> Summarising data by another variable</a></li>
<li class="chapter" data-level="2.8" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#plotting-data-by-another-variable"><i class="fa fa-check"></i><b>2.8</b> Plotting data by another variable</a></li>
<li class="chapter" data-level="2.9" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#recoding-data"><i class="fa fa-check"></i><b>2.9</b> Recoding data</a></li>
<li class="chapter" data-level="2.10" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#computing-binomial-probabilities-using-r"><i class="fa fa-check"></i><b>2.10</b> Computing binomial probabilities using R</a></li>
<li class="chapter" data-level="2.11" data-path="probability-and-probability-distributions.html"><a href="probability-and-probability-distributions.html#computing-probabilities-from-a-normal-distribution"><i class="fa fa-check"></i><b>2.11</b> Computing probabilities from a Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="precision-r-notes.html"><a href="precision-r-notes.html"><i class="fa fa-check"></i><b>3</b> Precision: R notes</a>
<ul>
<li class="chapter" data-level="3.1" data-path="precision-r-notes.html"><a href="precision-r-notes.html#calculating-a-95-confidence-interval-of-a-mean"><i class="fa fa-check"></i><b>3.1</b> Calculating a 95% confidence interval of a mean</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>4</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>4.1</b> One sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PHCM9795 Foundations of Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-r-and-rstudio" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Module 1</span> Introduction to R and RStudio<a href="introduction-to-r-and-rstudio.html#introduction-to-r-and-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="learning-outcomes" class="section level2 unnumbered hasAnchor">
<h2>Learning outcomes<a href="introduction-to-r-and-rstudio.html#learning-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>By the end of this Module, you will be able to:</p>
<ul>
<li>understand the difference between R and RStudio</li>
<li>navigate the RStudio interface</li>
<li>input and import data into R</li>
<li>use R to summarise data</li>
<li>perform basic data transformations</li>
<li>understand the difference between saving R data and saving R output</li>
<li>copy R output to a standard word processing package</li>
</ul>
</div>
<div id="part-1-an-introduction-to-r" class="section level2 unnumbered hasAnchor">
<h2>Part 1: An introduction to R<a href="introduction-to-r-and-rstudio.html#part-1-an-introduction-to-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>“R is a language and environment for statistical computing and graphics.” <a href="https://www.r-project.org/about.html">Link</a>. It is an open-source programming language, used mainly for statistics (including biostatistics) and data science.</p>
<p>The aim of these notes is to introduce the R language within the RStudio environment, and to introduce the commands and procedures that are directly relevant to this course. There is so much more to R than we can cover in these notes. Relevant information will be provided throughout the course, and we will provide further references that you can explore if you are interested.</p>
</div>
<div id="r-vs-rstudio" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> R vs RStudio<a href="introduction-to-r-and-rstudio.html#r-vs-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>At its heart, R is a programming language. When you install R on your computer, you are installing the language and its resources, as well as a very basic interface for using R. You can write and run R code using the basic R app, but it’s not recommended.</p>
<p>RStudio is an “Integrated Development Environment” that runs R while also providing useful tools to help you write code and analyse data. You can think of R as an engine which does the work, and RStudio as a car that uses the engine, but also provides useful tools like GPS navigation and reversing cameras that help you drive.</p>
<p>Note: even though we recommend that you use RStudio, you still need install R. <strong>RStudio will not run without R installed.</strong></p>
<table>
<colgroup>
<col width="44%" />
<col width="55%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">R: Don’t run this</th>
<th align="center">RStudio: Run this instead</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><img src="img/Rlogo.png" alt="R logo" style="height: 100px;"/></td>
<td align="center"><img src="img/RStudio-Logo-Flat.png" alt="RStudio logo" style="height: 100px;"/></td>
</tr>
</tbody>
</table>
</div>
<div id="installing-r-and-rstudio" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Installing R and RStudio<a href="introduction-to-r-and-rstudio.html#installing-r-and-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="to-install-r-on-your-computer" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> To install R on your computer<a href="introduction-to-r-and-rstudio.html#to-install-r-on-your-computer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Download the R installer from:</p>
<ol style="list-style-type: lower-alpha">
<li>for Windows: <a href="https://cran.r-project.org/bin/windows/base/" class="uri">https://cran.r-project.org/bin/windows/base/</a></li>
<li>for MacOS: <a href="https://cran.r-project.org/bin/macosx/" class="uri">https://cran.r-project.org/bin/macosx/</a></li>
</ol>
<ul>
<li><strong>Note for Windows users:</strong> as at May 27, 2022, R Version 4.2.0 has compatability issues with RStudio. You should download and install R from <a href="https://cran.r-project.org/bin/windows/base/rpatched.html" class="uri">https://cran.r-project.org/bin/windows/base/rpatched.html</a></li>
</ul></li>
<li><p>Install R by running the installer and following the installation instructions. The default settings are fine.</p>
<ul>
<li><strong>Note for macOS:</strong> if you are running macOS 10.8 or later, you will need to install an additional application called XQuartz, which is available at <a href="https://www.xquartz.org/" class="uri">https://www.xquartz.org/</a>. Download the latest installer (XQuartz-2.8.1.dmg as of April 2022), and install it in the usual way.</li>
</ul></li>
<li><p>Open the R program. You should see a screen as below:</p></li>
</ol>
<p><img src="img/R-screenshot.png" width="80%" /></p>
<p>Near the bottom of the R screen, you will find the “&gt;” symbol which represents the command line. If you type <code>1 + 2</code> into the command line and then hit enter you should get:</p>
<p><code>[1] 3</code></p>
<p>This is R performing your calculation, with the <code>[1]</code> indicating that the solution to <code>1 + 2</code> is a single number (the number 3).</p>
<p>At this point, close R - we will not interact with R like this in the future. You can close R by typing <code>quit()</code> at the command prompt, followed by the return key, or in the usual way of closing an application in your operating system. There is no need to save anything here if prompted.</p>
</div>
<div id="to-install-rstudio-on-your-computer" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> To install RStudio on your computer<a href="introduction-to-r-and-rstudio.html#to-install-rstudio-on-your-computer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Make sure you have already installed R, and verified that it is working.</li>
<li>Download the RStudio desktop installer at: <a href="https://www.rstudio.com/products/rstudio/download" class="uri">https://www.rstudio.com/products/rstudio/download</a>. Ensure that you select the RStudio Desktop (Free) installer in the first column.</li>
<li>Install RStudio by running the installer and following the installation instructions. The default settings are fine.</li>
<li>Open RStudio, which will appear as below:</li>
</ol>
<p><img src="img/RStudio-screenshot-01.png" width="100%" /></p>
<p>Locate the command line symbol “&gt;” at the bottom of the left-hand panel. Type <code>1 + 2</code> into the command line and hit enter, and you will see:</p>
<p><code>[1] 3</code></p>
<p>This confirms that RStudio is running correctly, and can use the R language to correctly calculate the sum between 1 and 2!</p>
<p>RStudio currently comprises three window panes, and we will discuss these later.</p>
</div>
</div>
<div id="recommended-setup" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Recommended setup<a href="introduction-to-r-and-rstudio.html#recommended-setup" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I will provide a recommended setup for R and RStudio in this section. You are free to use alternative workflows and setup, but this setup works well in practice.</p>
<div id="rstudio-preferences" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> RStudio preferences<a href="introduction-to-r-and-rstudio.html#rstudio-preferences" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>By default, RStudio will retain data, scripts and other objects when you quite your RStudio session. Relying on this can cause headaches, so I recommend that you set up RStudio so that it does not preserve your workspace between sessions. Open the RStudio options:</p>
<ul>
<li><p>Mac: <strong>RStudio &gt; Preferences</strong></p></li>
<li><p>Windows: <strong>Tools &gt; Options</strong></p></li>
</ul>
<p>and <strong>deselect “Restore .RData into workplace at startup”</strong>, and choose: “<strong>Save workspace to .RData on exit:</strong> <strong>Never”</strong>.</p>
<p><img src="img/RStudio-preferences.png" width="75%" /></p>
</div>
<div id="set-up-a-project" class="section level3 hasAnchor" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Set up a project<a href="introduction-to-r-and-rstudio.html#set-up-a-project" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A project in RStudio is a folder that RStudio recognises as a place to store R scripts, data files, figures that are common to an analysis project. Setting up a folder allows much more simple navigation and specification of data files and output. More detail can be found in Chapter 8 of the excellent text: <a href="https://r4ds.had.co.nz/workflow-projects.html">R for Data Science</a>. Using projects is not necessary, but I recommend working with projects from day one.</p>
<p>We will create a project called <strong>PHCM9795</strong> to store all the data you will use and scripts that you will write in this course. First, think about where you want to store your project folder: this could be somewhere in your <em>Documents</em> folder.</p>
<p>Step 1: Choose <strong>File &gt; New Project…</strong> in RStudio to open the <strong>Create Project</strong> dialog box:</p>
<p><img src="img/NewProject-1.png" width="75%" /></p>
<p>Step 2: Click the first option to create a project in a <strong>New directory</strong></p>
<p><img src="img/NewProject-2.png" width="75%" /></p>
<p>Step 3: Click the first option: <strong>New Project</strong>. Give the project a name, by typing PHCM9795 in the “Directory name”, and choose where you want to store the project by clicking the <strong>Browse</strong> button.</p>
<p><img src="img/NewProject-3.png" width="75%" /></p>
<p>Step 4: Click <strong>Create</strong> to create your project.</p>
<p>You will now have a new folder in your directory, which contains only one file: PHCM9795.Rproj, and the two right-hand panes of RStudio will appear as below:</p>
<p><img src="img/NewProject-4.png" width="75%" /></p>
<p>The top-right menu bar is showing that you are working within the PHCM9795 project, and the bottom-right window is showing the contents of that window: the single PHCM9795.Rproj file. We will add some more files to this project later.</p>
</div>
</div>
<div id="simpleR" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> A simple R analysis<a href="introduction-to-r-and-rstudio.html#simpleR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this very brief section, we will introduce R by calculating the average of six ages.</p>
<p>To begin, open a new R Script by choosing <strong>File &gt; New file &gt; R Script</strong> . A script (or a program) is a collection of commands that are sequentially processed by R. You can also type Ctrl+Shift+N in Windows, or Command+Shift+N in MacOS to open a new script in RStudio, or click the <strong>New File</strong> button at the top of the RStudio window.</p>
<p>You should now see four window panes, as below. In the top-left window, type the following (replacing my name with yours, and including today’s date):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="introduction-to-r-and-rstudio.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Author: Timothy Dobbins</span></span>
<span id="cb1-2"><a href="introduction-to-r-and-rstudio.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: 5 April 2022</span></span>
<span id="cb1-3"><a href="introduction-to-r-and-rstudio.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Purpose: My first R script</span></span>
<span id="cb1-4"><a href="introduction-to-r-and-rstudio.html#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="introduction-to-r-and-rstudio.html#cb1-5" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">23</span>, <span class="dv">29</span>, <span class="dv">21</span>, <span class="dv">27</span>)</span>
<span id="cb1-6"><a href="introduction-to-r-and-rstudio.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(age)</span></code></pre></div>
<p><strong>Note: R is case-sensitive</strong>, so you should enter the text exactly as written in these notes.</p>
<p>Your screen should look something like:</p>
<p><img src="img/RStudio-screenshot-02.png" width="100%" /></p>
<p>To run your script, choose <strong>Code &gt; Run Region &gt; Run All</strong>. You will see your code appear in the bottom-left window, with the following output:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="introduction-to-r-and-rstudio.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="co"># Author: Timothy Dobbins</span></span>
<span id="cb2-2"><a href="introduction-to-r-and-rstudio.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Date: 5 April 2022</span></span>
<span id="cb2-3"><a href="introduction-to-r-and-rstudio.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> <span class="co"># Purpose: My first R script</span></span>
<span id="cb2-4"><a href="introduction-to-r-and-rstudio.html#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> </span>
<span id="cb2-5"><a href="introduction-to-r-and-rstudio.html#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="er">&gt;</span> age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">23</span>, <span class="dv">29</span>, <span class="dv">21</span>, <span class="dv">27</span>)</span>
<span id="cb2-6"><a href="introduction-to-r-and-rstudio.html#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="introduction-to-r-and-rstudio.html#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(age)</span>
<span id="cb2-8"><a href="introduction-to-r-and-rstudio.html#cb2-8" aria-hidden="true" tabindex="-1"></a>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. </span>
<span id="cb2-9"><a href="introduction-to-r-and-rstudio.html#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fl">20.00</span>   <span class="fl">21.50</span>   <span class="fl">24.00</span>   <span class="fl">24.17</span>   <span class="fl">26.50</span>   <span class="fl">29.00</span> </span></code></pre></div>
<p>We will explain the key parts of this script later, but for now, you have entered six ages and calculated the mean age (along with five other summary statistics).</p>
<p>Save your script within the PHCM9795 project by using <strong>File &gt; Save As</strong>, using the name <code>my_first_analysis.R</code>.</p>
</div>
<div id="the-rstudio-environment" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> The RStudio environment<a href="introduction-to-r-and-rstudio.html#the-rstudio-environment" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have seen a simple example of how to use R within RStudio, let’s describe the RStudio environment. Let’s assume that you have just run your first R script, and you have four windows as below:</p>
<p><img src="img/RStudio-screenshot-03.png" width="100%" /></p>
<p>The top-left window is call the <strong>Source</strong> window, and is where you write and edit your R scripts. Scripts can be saved by clicking <strong>File &gt; Save As</strong> or by clicking on the symbol of a floppy disk at the top of the script. The file will have an extension of .R, for example script.R. Remember to give your script a meaningful title and remember to periodically save as you go.</p>
<p>In RStudio, the name of the script will be black when it has been saved, and will change to red if you have any unsaved changes.</p>
<p>The <strong>Console</strong> window, at the bottom left, contains the command line which is indicated with the symbol &gt;. You can type commands here, but anything executed directly from the console is not saved and therefore is lost when the session ends (when you exit RStudio). You should always run your commands from a script file which you can save and use again later. When you run commands from a script, the output and any notes/errors are shown in the console. The Terminal and Jobs tabs will not be used in this course.</p>
<p>The <strong>Environment</strong> window at the top-right shows a list of objects that have been created during your session. When you close your RStudio session these objects will disappear. We will not use the History or Connections tabs in this course.</p>
<p>The bottom right corner contains some useful tabs, in particular the <strong>Help</strong> tab. When you are troubleshooting errors or learning how to use a function, the Help tab should be the first place you visit. Here you can search the help documents for all the packages you have installed. Whenever you create plots in R, these will be shown in the <strong>Plots</strong> tab. The <strong>Packages</strong> tab contains a list of installed packages and indicates which ones are currently in use (we will learn about packages later). Packages which are loaded, i.e. in use, are indicated with a tick. Some packages are in use by default when you begin a new session. You can access information about a package by clicking on its name. The <strong>Files</strong> tab provides a shortcut to access your files. The Viewer tab will not be used in this course.</p>
</div>
<div id="some-r-basics" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Some R basics<a href="introduction-to-r-and-rstudio.html#some-r-basics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While we use R as a statistics package, R is a programming language. In order to use R effectively, we need to define some basics.</p>
<div id="scripts" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Scripts<a href="introduction-to-r-and-rstudio.html#scripts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>While R can be run completely from the command line, issuing commands one-by-one, it is most commonly run using <strong>scripts</strong>. A script is simply a list of commands that are processed in order. The simple analysis we conducted earlier is a very simple script. Some things to know about R scripts:</p>
<ul>
<li><p>anything appearing after a # is a comment, and is ignored by R. The first three lines of our script are there for ourselves (either as writers of code, or readers of code). I include comments at the beginning of each of my scripts to describe:</p>
<ul>
<li><p>who wrote the script (useful if someone else uses your script and wants to ask questions about it);</p></li>
<li><p>when the script was written;</p></li>
<li><p>what the script does. This last point may seem odd, but it’s useful to describe what this script does, and why it might differ to other scripts being used in the analysis. This is particularly useful if your scripts become long and complex.</p></li>
</ul></li>
<li><p><strong>R is case-sensitive</strong>. So <code>age</code>, <code>AGE</code> and <code>Age</code> could refer to three separate variables (please don’t do this!)</p></li>
<li><p>use blank lines and comments to separate sections of your script</p></li>
</ul>
</div>
<div id="objects" class="section level3 hasAnchor" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Objects<a href="introduction-to-r-and-rstudio.html#objects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you do some reading about R, you may learn that R is an “object-oriented programming language”. When we enter or import data into R, we are asking R to create <strong>objects</strong> from our data. These objects can be manipulated and transformed by <strong>functions</strong>, to obtain useful insights from our data.</p>
<p>Objects in R are created using the <strong>assignment operator</strong>. The most common form of the assignment operator looks like an arrow: <code>&lt;-</code> and is typed as the <code>&lt;</code> and <code>-</code> symbols. The simplest way of reading <code>&lt;-</code> is as the words “is defined as”. Note that it possible to use <code>-&gt;</code> and even <code>=</code> as assignment operators, but their use is less frequent.</p>
<p>Let’s see an example:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="introduction-to-r-and-rstudio.html#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">42</span></span></code></pre></div>
<p>This command creates a new object called <code>x</code>, which is defined as the number 42 (or in words, “<code>x</code> is defined as 42”). Running this command gives no output in the console, but the new object appears in the top-right <strong>Environment</strong> panel. We can view the object in the console by typing its name:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="introduction-to-r-and-rstudio.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the object x</span></span>
<span id="cb4-2"><a href="introduction-to-r-and-rstudio.html#cb4-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 42</code></pre>
<p>Now we see the contents of <code>x</code> in the console.</p>
<p>This example is rather trivial, and we rarely assign objects of just one value. In fact, we created an object earlier, called <code>age</code>, which comprised six values.</p>
</div>
<div id="data-structures" class="section level3 hasAnchor" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Data structures<a href="introduction-to-r-and-rstudio.html#data-structures" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are two main structures we will use to work with data in this course: <strong>vectors</strong> and <strong>data frames</strong>. A <strong>vector</strong> is a combination of data values, all of the same type. For example, our six ages that we entered earlier is a vector. You could think of a vector as a column of data (even though R prints vectors as rows!) And technically, even an object with only one value is a vector, a vector of size 1.</p>
<p>The easiest way of creating a vector in R is by using the <code>c()</code> function, where c stands for ‘combine’. In our previous Simple Analysis in R (Section <a href="introduction-to-r-and-rstudio.html#simpleR">1.4</a>), we wrote the command:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="introduction-to-r-and-rstudio.html#cb6-1" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">23</span>, <span class="dv">29</span>, <span class="dv">21</span>, <span class="dv">27</span>)</span></code></pre></div>
<p>This command created a new object called <code>age</code>, and <em>combined</em> the six values of age into one vector.</p>
<p>Just as having a vector of size 1 is unusual, having just one column of data to analyse is also pretty unusual. The other structure we will describe here is a <strong>data frame</strong> which is essentially a collection of vectors, each of the same size. You could think of a data frame as being like a spreadsheet, with columns representing variables, and rows representing observations.</p>
<p>There are other structures in R, such as matrices and lists, which we won’t discuss in this course. And you may come across the term <strong>tibble</strong>, which is a type of data frame.</p>
</div>
<div id="functions" class="section level3 hasAnchor" number="1.6.4">
<h3><span class="header-section-number">1.6.4</span> Functions<a href="introduction-to-r-and-rstudio.html#functions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If objects are the nouns of R, functions are the verbs. Essentially, functions transform objects. Functions can transform your data into summary statistics, graphical summaries or analysis results. For example, we used the <code>summary()</code> function to display summary statistics for our six ages.</p>
<p>R functions are specified by their arguments (or inputs). The arguments that can be supplied for each function can be inspected by examining the help notes for that function. To obtain help for a function, we can submit <code>help(summary)</code> (or equivalently <code>?summary</code>) in the console, or we can use the <strong>Help</strong> tab in the bottom-right window of RStudio. For example, the first part of the help notes for <code>summary</code> appear as:</p>
<p><img src="img/help-1.png" width="80%" /></p>
<p>The help notes in R can be quite cryptic, but the <strong>Usage</strong> section details what inputs should be specified for the function to run. Here, <code>summary</code> requires an object to be specified. In our case, we specified <code>age</code>, which is our object defined as the vector of six ages.</p>
<p>Most help pages also include some examples of how you might use the function. These can be found at the very bottom of the help page.</p>
<p><img src="img/help-2.png" width="80%" /></p>
<p>The <code>summary()</code> function is quite simple, in that it only requires one input, the object to be summarised. More complex functions might require a number of inputs. For example, the help notes for the <code>descriptives()</code> function in the <code>jmv</code> package show a large number of inputs can be specified:</p>
<p><img src="img/help-3.png" width="80%" /></p>
<p>There are two things to note here. First, notice that the first two inputs are listed with no = symbol, but all other inputs are listed with = symbols (with values provided after the = symbol). This means that everything apart from <code>data</code> and <code>vars</code> have <strong>default</strong> values. We are free to not specify values for these inputs if we are happy with the defaults provided. For example, by default the variance is not calculated (as <code>variance = FALSE</code>). To obtain the variance as well as the standard deviation, we can change this default to <code>variance = TRUE</code>:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="introduction-to-r-and-rstudio.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Only the standard deviation is provided as the measure of variability</span></span>
<span id="cb7-2"><a href="introduction-to-r-and-rstudio.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>pbc, <span class="at">vars=</span>age)</span>
<span id="cb7-3"><a href="introduction-to-r-and-rstudio.html#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="introduction-to-r-and-rstudio.html#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Additionally request the variance to be calculated</span></span>
<span id="cb7-5"><a href="introduction-to-r-and-rstudio.html#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>pbc, <span class="at">vars=</span>age, <span class="at">variance=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>Second, for functions with multiple inputs, we can specify the input name and its value, or we can ignore the input name and specify just the input values <strong>in the order listed in the Usage section</strong>. So the following are equivalent:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="introduction-to-r-and-rstudio.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can specify that the dataset to be summarised is pbc,</span></span>
<span id="cb8-2"><a href="introduction-to-r-and-rstudio.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   and the variable to summarise is age:</span></span>
<span id="cb8-3"><a href="introduction-to-r-and-rstudio.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>pbc, <span class="at">vars=</span>age)</span>
<span id="cb8-4"><a href="introduction-to-r-and-rstudio.html#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="introduction-to-r-and-rstudio.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We can omit the input name, as long as we keep the inputs in the correct order - </span></span>
<span id="cb8-6"><a href="introduction-to-r-and-rstudio.html#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   that is, dataset first, variable second:</span></span>
<span id="cb8-7"><a href="introduction-to-r-and-rstudio.html#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(pbc, age)</span>
<span id="cb8-8"><a href="introduction-to-r-and-rstudio.html#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="introduction-to-r-and-rstudio.html#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># We can change the order of the inputs, as long as we specify the input name:</span></span>
<span id="cb8-10"><a href="introduction-to-r-and-rstudio.html#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">vars=</span>age, <span class="at">data=</span>pbc)</span></code></pre></div>
<p>In this course, we will usually provide all the input names, even when they are not required. As you become more familiar with R, you will start to use the shortcut method.</p>
<div id="the-curse-of-inconsistency" class="section level4 hasAnchor" number="1.6.4.1">
<h4><span class="header-section-number">1.6.4.1</span> The curse of inconsistency<a href="introduction-to-r-and-rstudio.html#the-curse-of-inconsistency" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As R is an open-source project, many people have contributed to its development. This has led to a frustrating part of R: some functions require a single object to be specified, but some require you to specify a data frame and select variables for analysis. Let’s see an example.</p>
<p>The help for <code>summary()</code> specifies the usage as: <code>summary(object, ...)</code>. This means we need to specify a single object to be summarised. An object could be a single column of data (i.e. a vector), or it could be a data frame. If we have a data frame called <code>pbc</code> which contains many variables, the command <code>summary(pbc)</code> would summarise every variable in the data frame.</p>
<p>What if we only wanted to summarise the age of the participants in the data frame? To select a single variable from a data frame, we can use the following syntax: <code>dataframe$variable</code>. So to summarise just age from this data frame, we would use: <code>summary(pbc$age)</code>.</p>
<p>Compare this with the <code>descriptives()</code> function in the <code>jmv</code> package. We saw earlier that the two required inputs for <code>descriptives()</code> are <code>data</code> (the data frame to be analysed) and <code>vars</code> (the variables to be analysed). So to summarise <code>age</code> from the <code>pbc</code> data frame, we would specify <code>descriptives(data=pbc, vars=age)</code>.</p>
<p>This inconsistency will seem maddening at first, and will continue to be maddening! Reading the <strong>usage</strong> section of the help pages is a useful way to determine whether you should specify an object (like <code>pbc$age</code>) or a data frame and a list of variables.</p>
</div>
</div>
<div id="packages" class="section level3 hasAnchor" number="1.6.5">
<h3><span class="header-section-number">1.6.5</span> Packages<a href="introduction-to-r-and-rstudio.html#packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>package</strong> is a collection of functions, documentation (and sometimes datasets) that extend the capabilities of R. Packages have been written by R users to be freely distributed and used by others. R packages can be obtained from many sources, but the most common source is CRAN: the Comprehensive R Archive Network.</p>
<p>A useful way of thinking about R is that R is like a smartphone, with packages being like apps which are downloaded from CRAN (similar to an app-store). When you first install R, it comes with a basic set of packages (apps) installed. You can do a lot of things with these basic packages, but sometimes you might want to do things differently, or you may want to perform some analyses that can’t be done using the default packages. In these cases, you can install a package.</p>
<p>Like installing an app on a smartphone, you only need to <em>install</em> a package once. But each time you want to use the package, you need to <em>load</em> the package into R.</p>
</div>
<div id="how-to-install-a-package" class="section level3 hasAnchor" number="1.6.6">
<h3><span class="header-section-number">1.6.6</span> How to install a package<a href="introduction-to-r-and-rstudio.html#how-to-install-a-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are a couple of ways to install a package. You can use the <code>install.packages()</code> function if you know the exact name of the package. Let’s use an example of installing the <code>skimr</code> package, which gives a very nice, high-level overview of any data frame. We can install <code>skimr</code> by typing the following into the console:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="introduction-to-r-and-rstudio.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;skimr&quot;</span>)</span></code></pre></div>
<p>Note the use of the quotation marks.</p>
<p>Alternatively, RStudio offers a graphical way of installing packages that can be accessed via <strong>Tools &gt; Install Packages</strong>, or via the <strong>Install</strong> button at the top of the <strong>Packages</strong> tab in the bottom-right window. You can begin typing the name of the package in the dialog box that appears, and RStudio will use predictive text to offer possible packages:</p>
<p><img src="img/install-packages.png" width="60%" /></p>
<p>While writing code is usually the recommended way to use R, installing packages is an exception. Using <strong>Tools &gt; Install Packages</strong> is perfectly fine, because you only need to install a package once.</p>
</div>
<div id="how-to-load-a-package" class="section level3 hasAnchor" number="1.6.7">
<h3><span class="header-section-number">1.6.7</span> How to load a package<a href="introduction-to-r-and-rstudio.html#how-to-load-a-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you begin a new session in RStudio, i.e. when you open RStudio, only certain core packages are automatically loaded. You can use the <code>library()</code> function to load a package that you has previously been installed. For example, now that we have installed <code>skimr</code>, we need to load it before we can use it:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="introduction-to-r-and-rstudio.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code></pre></div>
<p>Note that quotation marks are not required for the <code>library()</code> function (although they can be included if you really like quotation marks!).</p>
<div id="installing-vs-loading-packages" class="section level4 unnumbered hasAnchor">
<h4>Installing vs loading packages<a href="introduction-to-r-and-rstudio.html#installing-vs-loading-packages" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Package installation:</p>
<ul>
<li>use the <code>install.packages()</code> function (note the ‘s’) or <strong>Tools &gt; Install packages</strong></li>
<li>the package name must be surrounded by quotation marks</li>
<li>only needs to be done once</li>
</ul>
<p>Package loading</p>
<ul>
<li>use the <code>library()</code> function</li>
<li>the package name does not need to be surrounded by quotation marks</li>
<li>must be done for each R session</li>
</ul>
</div>
</div>
</div>
<div id="what-is-this-thing-called-the-tidyverse" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> What is this thing called the tidyverse?<a href="introduction-to-r-and-rstudio.html#what-is-this-thing-called-the-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you have done much reading about R, you may have come across the tidyverse:</p>
<blockquote>
<p>“The tidyverse is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures.” <a href="https://www.tidyverse.org/" class="uri">https://www.tidyverse.org/</a></p>
</blockquote>
<p>Packages in the tidyverse have been designed with a goal to make using R more consistent by defining a “grammar” to manipulate data, examine data and draw conclusions from data. While the tidyverse is a common and powerful set of packages, we will not be teaching the tidyverse in this course for two main reasons:</p>
<ol style="list-style-type: decimal">
<li>The data we provide have been saved in a relatively tidy way, and do not need much manipulation for analyses to be conducted. The cognitive load in learning the tidyverse in this course is greater than the benefit that could be gained.</li>
<li>There are many resources (online, in print etc) that are based on <code>base R</code>, and do not use the tidyverse. It would be difficult to understand these resources if we taught only tidyverse techniques. In particular, the <code>dataframe$variable</code> syntax is an important concept that should be understood before moving into the tidyverse.</li>
</ol>
<p>In saying all of this, I think the tidyverse is an excellent set of packages, which I frequently use. At the completion of this course, you will be well equipped to teach yourself tidyverse using many excellent resources such as: <a href="https://jhudatascience.org/tidyversecourse/">Tidyverse Skills for Data Science</a> and <a href="https://r4ds.had.co.nz/">R for Data Science</a>.</p>
</div>
<div id="part-2-obtaining-basic-descriptive-statistics" class="section level2 unnumbered hasAnchor">
<h2>Part 2: Obtaining basic descriptive statistics<a href="introduction-to-r-and-rstudio.html#part-2-obtaining-basic-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this exercise, we will analyse data to complete a descriptive table from a research study. The data come from a study in primary biliary cirrhosis, a condition of the liver, from Modeling Survival Data: Extending the Cox Model <span class="citation">Therneau and Grambsch (<a href="#ref-therneau_grambsch10" role="doc-biblioref">2010</a>)</span>. By the end of this exercise, we will have completed the following table.</p>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 95%; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-23">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-23">Table 1.1: </span> Summary of 418 participants from the PBC study (Therneau and Grambsch, 2000)</caption><col><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 0pt; font-weight: bold;">Characteristic</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;"> </th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 0pt 6pt 6pt; font-weight: bold;">Summary</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Age (years)</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 0pt 6pt 6pt; font-weight: normal;">Mean (SD) or Median [IQR]</td></tr>
<tr>
<td rowspan="2" style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Sex</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Male</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Female</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">AST* (U/ml)</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">Mean (SD) or Median [IQR]</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Serum bilirubin</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">Mean (SD) or Median [IQR]</td></tr>
<tr>
<td rowspan="4" style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Stage</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">I</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">II</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">III</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">IIIV</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td rowspan="3" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Vital status at study end</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Alive: no transplant</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Alive: transplant</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Deceased</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 0pt 6pt 6pt; font-weight: normal;">n (%)</td></tr>
<tr>
<td colspan="3" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">* asparate aminotransferase</td></tr>
</table>

<p>This table is available in Table1.docx, saved on Moodle.</p>
</div>
<div id="set-up-your-data" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Set up your data<a href="introduction-to-r-and-rstudio.html#set-up-your-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We created a project in the previous step. We will now create a folder to store all the data for this course. Storing the data within the project makes life much easier!</p>
<p>Create a new folder by clicking the <strong>New Folder</strong> icon in the <strong>Files</strong> tab at the bottom-right:</p>
<p><img src="img/NewFolder-1.png" width="75%" /></p>
<p>Call the new folder <strong>data</strong>.</p>
<p>Click on this folder to open it, and then create two new folders: <strong>activities</strong> and <strong>examples</strong>.</p>
<p>Download the “Data sets: for learning activities” from Moodle, and use Windows Explorer or MacOS Finder to save these data sets in <strong>activities</strong>. Save the “Data sets: example data from course notes” into the <strong>examples</strong> folder.</p>
<p>Your <strong>activities</strong> folder should look like:</p>
<p><img src="img/data-folder.png" width="75%" /></p>
<p>Click the two dots next to the up-arrow at the top of the folder contents to move back up the folder structure. Note that you need to click the dots, and not the up-facing green arrow!</p>
</div>
<div id="reading-a-data-file" class="section level2 hasAnchor" number="1.9">
<h2><span class="header-section-number">1.9</span> Reading a data file<a href="introduction-to-r-and-rstudio.html#reading-a-data-file" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Typing data directly into R is not common; we usually read data that have been previously saved. In this example, we will read an <code>.rds</code> file using the <code>readRDS()</code> function, which has only one input: the location of the file.</p>
<p>1 - Confirm that the <code>pbc.rds</code> file is in the <code>activities</code> sub-folder within the <code>data</code> folder (as per the previous steps).</p>
<p>2 - Install the packages: <code>jmv</code>, <code>skimr</code> and <code>summarytools</code> using <strong>Tools &gt; Install packages</strong>, or by typing into the console:</p>
<p><code>install.packages("jmv")</code></p>
<p><code>install.packages("skimr")</code></p>
<p><code>install.packages("summarytools")</code></p>
<p>3 - Load the <code>skimr</code> package, and use the <code>readRDS()</code> function to read the file into R, assigning it to a data frame called <code>pbc</code>. Because we set up our project, we can locate our data easily by telling R to use the file: <code>"data/activities/pbc.rds"</code>, which translates as: the file <code>pbc.rds</code> which is located in the <code>activities</code> sub-folder within the <code>data</code> folder.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="introduction-to-r-and-rstudio.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb11-2"><a href="introduction-to-r-and-rstudio.html#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="introduction-to-r-and-rstudio.html#cb11-3" aria-hidden="true" tabindex="-1"></a>pbc <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/activities/pbc.rds&quot;</span>)</span></code></pre></div>
<p>4 - We can now use the <code>summary()</code> function to examine the pbc dataset:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="introduction-to-r-and-rstudio.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pbc)</span></code></pre></div>
<pre><code>##        id             time          status            trt       
##  Min.   :  1.0   Min.   :  41   Min.   :0.0000   Min.   :1.000  
##  1st Qu.:105.2   1st Qu.:1093   1st Qu.:0.0000   1st Qu.:1.000  
##  Median :209.5   Median :1730   Median :0.0000   Median :1.000  
##  Mean   :209.5   Mean   :1918   Mean   :0.8301   Mean   :1.494  
##  3rd Qu.:313.8   3rd Qu.:2614   3rd Qu.:2.0000   3rd Qu.:2.000  
##  Max.   :418.0   Max.   :4795   Max.   :2.0000   Max.   :2.000  
##                                                  NA&#39;s   :106    
##       age             sex           ascites            hepato      
##  Min.   :26.28   Min.   :1.000   Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:42.83   1st Qu.:2.000   1st Qu.:0.00000   1st Qu.:0.0000  
##  Median :51.00   Median :2.000   Median :0.00000   Median :1.0000  
##  Mean   :50.74   Mean   :1.895   Mean   :0.07692   Mean   :0.5128  
##  3rd Qu.:58.24   3rd Qu.:2.000   3rd Qu.:0.00000   3rd Qu.:1.0000  
##  Max.   :78.44   Max.   :2.000   Max.   :1.00000   Max.   :1.0000  
##                                  NA&#39;s   :106       NA&#39;s   :106     
##     spiders           edema             bili             chol       
##  Min.   :0.0000   Min.   :0.0000   Min.   : 0.300   Min.   : 120.0  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.: 0.800   1st Qu.: 249.5  
##  Median :0.0000   Median :0.0000   Median : 1.400   Median : 309.5  
##  Mean   :0.2885   Mean   :0.1005   Mean   : 3.221   Mean   : 369.5  
##  3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.: 3.400   3rd Qu.: 400.0  
##  Max.   :1.0000   Max.   :1.0000   Max.   :28.000   Max.   :1775.0  
##  NA&#39;s   :106                                        NA&#39;s   :134     
##     albumin          copper          alkphos             ast        
##  Min.   :1.960   Min.   :  4.00   Min.   :  289.0   Min.   : 26.35  
##  1st Qu.:3.243   1st Qu.: 41.25   1st Qu.:  871.5   1st Qu.: 80.60  
##  Median :3.530   Median : 73.00   Median : 1259.0   Median :114.70  
##  Mean   :3.497   Mean   : 97.65   Mean   : 1982.7   Mean   :122.56  
##  3rd Qu.:3.770   3rd Qu.:123.00   3rd Qu.: 1980.0   3rd Qu.:151.90  
##  Max.   :4.640   Max.   :588.00   Max.   :13862.4   Max.   :457.25  
##                  NA&#39;s   :108      NA&#39;s   :106       NA&#39;s   :106     
##       trig           platelet        protime          stage      
##  Min.   : 33.00   Min.   : 62.0   Min.   : 9.00   Min.   :1.000  
##  1st Qu.: 84.25   1st Qu.:188.5   1st Qu.:10.00   1st Qu.:2.000  
##  Median :108.00   Median :251.0   Median :10.60   Median :3.000  
##  Mean   :124.70   Mean   :257.0   Mean   :10.73   Mean   :3.024  
##  3rd Qu.:151.00   3rd Qu.:318.0   3rd Qu.:11.10   3rd Qu.:4.000  
##  Max.   :598.00   Max.   :721.0   Max.   :18.00   Max.   :4.000  
##  NA&#39;s   :136      NA&#39;s   :11      NA&#39;s   :2       NA&#39;s   :6</code></pre>
<p>An alternative to the <code>summary()</code> function is the <code>skim()</code> function in the <code>skimr</code> package, which produces summary statistics as well as rudimentary histograms:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="introduction-to-r-and-rstudio.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(pbc)</span></code></pre></div>
<p><img src="img/skim-pbc.png" width="90%" /></p>
<p>The <code>summary()</code> and <code>skim()</code> functions are useful to give a quick overview of a dataset: how many variables are included, how variables are coded, which variables contain missing data and a crude histogram showing the distribution of numeric variables.</p>
</div>
<div id="summarising-continuous-variables" class="section level2 hasAnchor" number="1.10">
<h2><span class="header-section-number">1.10</span> Summarising continuous variables<a href="introduction-to-r-and-rstudio.html#summarising-continuous-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the most flexible functions for summarising continuous variables is the <code>descriptives()</code> function from the <code>jmv</code> package. The function is specified as <code>descriptives(data=, vars=)</code> where:</p>
<ul>
<li><code>data</code> specifies the dataframe to be analysed</li>
<li><code>vars</code> specifies the variable(s) of interest, with multiple variables combined using the <code>c()</code> function</li>
</ul>
<p>We can summarise the three continuous variables in the pbc data: age, AST and serum bilirubin, as shown below.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="introduction-to-r-and-rstudio.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb15-2"><a href="introduction-to-r-and-rstudio.html#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="introduction-to-r-and-rstudio.html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>pbc, <span class="at">vars=</span><span class="fu">c</span>(age, ast, bili))</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                
##  ─────────────────────────────────────────────────────────── 
##                          age         ast         bili        
##  ─────────────────────────────────────────────────────────── 
##    N                          418         312          418   
##    Missing                      0         106            0   
##    Mean                  50.74155    122.5563     3.220813   
##    Median                51.00068    114.7000     1.400000   
##    Standard deviation    10.44721    56.69952     4.407506   
##    Minimum               26.27789    26.35000    0.3000000   
##    Maximum               78.43943    457.2500     28.00000   
##  ───────────────────────────────────────────────────────────</code></pre>
<p>By default, the <code>descriptives</code> function presents the mean, median, standard deviation, minimum and maximum. We can request additional statistics, such as the quartiles (which are called the percentiles, or pc, in the descriptives function):</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="introduction-to-r-and-rstudio.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>pbc, <span class="at">vars=</span><span class="fu">c</span>(age, ast, bili), <span class="at">pc=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                
##  ─────────────────────────────────────────────────────────── 
##                          age         ast         bili        
##  ─────────────────────────────────────────────────────────── 
##    N                          418         312          418   
##    Missing                      0         106            0   
##    Mean                  50.74155    122.5563     3.220813   
##    Median                51.00068    114.7000     1.400000   
##    Standard deviation    10.44721    56.69952     4.407506   
##    Minimum               26.27789    26.35000    0.3000000   
##    Maximum               78.43943    457.2500     28.00000   
##    25th percentile       42.83231    80.60000    0.8000000   
##    50th percentile       51.00068    114.7000     1.400000   
##    75th percentile       58.24093    151.9000     3.400000   
##  ───────────────────────────────────────────────────────────</code></pre>
</div>
<div id="producing-a-histogram" class="section level2 hasAnchor" number="1.11">
<h2><span class="header-section-number">1.11</span> Producing a histogram<a href="introduction-to-r-and-rstudio.html#producing-a-histogram" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can use the <code>hist()</code> function to produce a histogram, specifying the dataframe to use and the variable to be plotted as <code>dataframe$variable</code>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="introduction-to-r-and-rstudio.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(pbc<span class="sc">$</span>age)</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>The histogram function does a remarkably good job of choosing cutpoints and binwidths, and these rarely need to be changed. However, the labelling of the histogram should be improved by using <code>xlab=" "</code> and <code>main=" "</code> to assign labels for the x-axis and overall title respectively:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="introduction-to-r-and-rstudio.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(pbc<span class="sc">$</span>age, <span class="at">xlab=</span><span class="st">&quot;Age (years)&quot;</span>, </span>
<span id="cb20-2"><a href="introduction-to-r-and-rstudio.html#cb20-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Histogram of participant age from pbc study data&quot;</span>)</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
<div id="producing-a-boxplot" class="section level2 hasAnchor" number="1.12">
<h2><span class="header-section-number">1.12</span> Producing a boxplot<a href="introduction-to-r-and-rstudio.html#producing-a-boxplot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>boxplot</code> function is used to produce boxplots, again specifying the dataframe to use and the variable to be plotted as <code>dataframe$variable</code>. Labels can be applied in the same way as the histogram:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="introduction-to-r-and-rstudio.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(pbc<span class="sc">$</span>age, <span class="at">xlab=</span><span class="st">&quot;Age (years)&quot;</span>, <span class="at">main=</span><span class="st">&quot;Boxplot of participant age from pbc study data&quot;</span>)</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
</div>
<div id="producing-a-one-way-frequency-table" class="section level2 hasAnchor" number="1.13">
<h2><span class="header-section-number">1.13</span> Producing a one-way frequency table<a href="introduction-to-r-and-rstudio.html#producing-a-one-way-frequency-table" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have three categorical variables to summarise in Table 1: sex, stage and vital status. These variables are best summarised using one-way frequency tables.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="introduction-to-r-and-rstudio.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb22-2"><a href="introduction-to-r-and-rstudio.html#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="introduction-to-r-and-rstudio.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(pbc<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## Frequencies  
## pbc$sex  
## Type: Numeric  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           1     44     10.53          10.53     10.53          10.53
##           2    374     89.47         100.00     89.47         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    418    100.00         100.00    100.00         100.00</code></pre>
<div id="defining-categorical-variables-as-factors" class="section level3 hasAnchor" number="1.13.1">
<h3><span class="header-section-number">1.13.1</span> Defining categorical variables as factors<a href="introduction-to-r-and-rstudio.html#defining-categorical-variables-as-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You will notice that the table above, in its current form, is uninterpretable as the 1 and 2 categories are not labelled. In this course, all variables including categorical variables tend to be numerically coded. To define a categorical variable as such in R, we define it as a <strong>factor</strong> using the factor function:</p>
<p><code>factor(variable=, levels=, labels=)</code></p>
<p>We specify:</p>
<ul>
<li>levels: the values the categorical variable can take</li>
<li>labels: the labels corresponding to each of the levels (entered in the same order as the levels)</li>
</ul>
<p>To define our variable sex as a factor, we use:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="introduction-to-r-and-rstudio.html#cb24-1" aria-hidden="true" tabindex="-1"></a>pbc<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(pbc<span class="sc">$</span>sex, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>))</span></code></pre></div>
<p>We can confirm the coding by re-running a frequency table:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="introduction-to-r-and-rstudio.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(pbc<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## Frequencies  
## pbc$sex  
## Type: Factor  
## 
##                Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ------------ ------ --------- -------------- --------- --------------
##         Male     44     10.53          10.53     10.53          10.53
##       Female    374     89.47         100.00     89.47         100.00
##         &lt;NA&gt;      0                               0.00         100.00
##        Total    418    100.00         100.00    100.00         100.00</code></pre>
<blockquote>
<p>Task: define Stage and Vital Status as factors, and produce one-way frequency tables. For example, for Stage:</p>
</blockquote>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="introduction-to-r-and-rstudio.html#cb27-1" aria-hidden="true" tabindex="-1"></a>pbc<span class="sc">$</span>stage <span class="ot">&lt;-</span> <span class="fu">factor</span>(pbc<span class="sc">$</span>stage, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Stage 1&quot;</span>, <span class="st">&quot;Stage 2&quot;</span>, <span class="st">&quot;Stage 3&quot;</span>, <span class="st">&quot;Stage 4&quot;</span>))</span>
<span id="cb27-2"><a href="introduction-to-r-and-rstudio.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(pbc<span class="sc">$</span>stage)</span></code></pre></div>
<pre><code>## Frequencies  
## pbc$stage  
## Type: Factor  
## 
##                 Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ------------- ------ --------- -------------- --------- --------------
##       Stage 1     21      5.10           5.10      5.02           5.02
##       Stage 2     92     22.33          27.43     22.01          27.03
##       Stage 3    155     37.62          65.05     37.08          64.11
##       Stage 4    144     34.95         100.00     34.45          98.56
##          &lt;NA&gt;      6                               1.44         100.00
##         Total    418    100.00         100.00    100.00         100.00</code></pre>
</div>
</div>
<div id="producing-a-two-way-frequency-table" class="section level2 hasAnchor" number="1.14">
<h2><span class="header-section-number">1.14</span> Producing a two-way frequency table<a href="introduction-to-r-and-rstudio.html#producing-a-two-way-frequency-table" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To produce tables summarising two categorical variables, we can use the <code>contTables()</code> function within the <code>jmv</code> package. The minimal inputs to include are <code>data</code>: the name of the data frame to be analysed, <code>rows</code>: the variable representing the rows of the table, and <code>cols</code>: the name of the columns of the table.</p>
<p>For example, to produce a two-way table showing stage of disease by sex using the pbc data frame, we use:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="introduction-to-r-and-rstudio.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contTables</span>(<span class="at">data=</span>pbc, <span class="at">rows=</span>sex, <span class="at">cols=</span>stage)</span></code></pre></div>
<pre><code>## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                                              
##  ─────────────────────────────────────────────────────────────── 
##    sex       Stage 1    Stage 2    Stage 3    Stage 4    Total   
##  ─────────────────────────────────────────────────────────────── 
##    Male            3          8         16         17       44   
##    Female         18         84        139        127      368   
##    Total          21         92        155        144      412   
##  ─────────────────────────────────────────────────────────────── 
## 
## 
##  χ² Tests                               
##  ────────────────────────────────────── 
##          Value        df    p           
##  ────────────────────────────────────── 
##    χ²    0.8779873     3    0.8307365   
##    N           412                      
##  ──────────────────────────────────────</code></pre>
<p>[The bottom part of the output, χ² Tests, can be ignored for now]</p>
<p>You may notice in the above that the number of observations is now 412. This is because there are missing observations for either sex or stage: which is it, and how would you determine this?</p>
<p>From the cross-tabulation, you can see the individual frequencies of participants in each of the categories in each cell. For example, there are 3 male participants who have Stage 1 disease. You can also read the totals for each row and column. For example, there are 44 males, and 144 participants have Stage 4 disease.</p>
<p>You can also add percentages into your table using <code>pcCol=TRUE</code> to include column percents, and <code>pcRow=TRUE</code> for row percents. For example, to calculate the relative frequencies (i.e. percentages) of sex within each stage, we would request <strong>column percents</strong> with the option: <code>pcCol=TRUE</code>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="introduction-to-r-and-rstudio.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contTables</span>(<span class="at">data=</span>pbc, <span class="at">rows=</span>sex, <span class="at">cols=</span>stage, <span class="at">pcCol=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                                                                             
##  ────────────────────────────────────────────────────────────────────────────────────────────── 
##    sex                          Stage 1      Stage 2      Stage 3      Stage 4      Total       
##  ────────────────────────────────────────────────────────────────────────────────────────────── 
##    Male      Observed                   3            8           16           17           44   
##              % within column     14.28571      8.69565     10.32258     11.80556     10.67961   
##                                                                                                 
##    Female    Observed                  18           84          139          127          368   
##              % within column     85.71429     91.30435     89.67742     88.19444     89.32039   
##                                                                                                 
##    Total     Observed                  21           92          155          144          412   
##              % within column    100.00000    100.00000    100.00000    100.00000    100.00000   
##  ────────────────────────────────────────────────────────────────────────────────────────────── 
## 
## 
##  χ² Tests                               
##  ────────────────────────────────────── 
##          Value        df    p           
##  ────────────────────────────────────── 
##    χ²    0.8779873     3    0.8307365   
##    N           412                      
##  ──────────────────────────────────────</code></pre>
<p>We can see that the 3 male participants with Stage 1 disease represent 14% of those with Stage 1 disease.</p>
</div>
<div id="saving-data-in-r" class="section level2 hasAnchor" number="1.15">
<h2><span class="header-section-number">1.15</span> Saving data in R<a href="introduction-to-r-and-rstudio.html#saving-data-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are many ways to save data from R, depending on the type of file you want to save. The recommendation for this course is to save your data using the <code>.rds</code> format, using the <code>saveRDS()</code> function, which takes two inputs: <code>saveRDS(object, file)</code>. Here, <code>object</code> is the R object to be saved (usually a data frame), and <code>file</code> is the location for the file to be saved (file name and path, including the <code>.rds</code> suffix).</p>
<p>It is not necessary to save our PBC data, as we have made only minor changes to the data that can be replicated by rerunning our script. If you had made major changes and wanted to save your data, you could use:</p>
<p><code>saveRDS(pbc, file="pbc_revised.rds")</code></p>
</div>
<div id="copying-output-from-r" class="section level2 hasAnchor" number="1.16">
<h2><span class="header-section-number">1.16</span> Copying output from R<a href="introduction-to-r-and-rstudio.html#copying-output-from-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is important to note that saving your data or your script in R will not save your output. The easiest way to retain the output of your analyses is to copy the output from the Console into a word processor package (e.g. Microsoft Word) before closing R.</p>
<p>Unfortunately, by default, R is not ideal for creating publication quality tables. There are many packages that will help in this process, such as R Markdown, bookdown<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>, huxtable, gt and gtsummary, but their use is beyond the scope of this course. <a href="https://rmd4sci.njtierney.com/">R Markdown for Scientists</a> provides an excellent introduction to R Markdown.</p>
<blockquote>
<p>Task: Complete Table 1 using the output generated in this exercise. You should decide on whether to present continuous variables by their means or medians, and present the most appropriate measure of spread. Include footnotes to indicate if any variables contain missing observations.</p>
</blockquote>
</div>
<div id="part-3-creating-other-types-of-graphs" class="section level2 unnumbered hasAnchor">
<h2>Part 3: Creating other types of graphs<a href="introduction-to-r-and-rstudio.html#part-3-creating-other-types-of-graphs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>plot()</code> function, also known as <em>base graphics</em>, is the default method of plotting data in R that can produce publication-quality graphics with minimal coding. There are alternative packages for plotting, with <code>ggplot2</code> being one of the most well known. We will present instructions for base graphics in this course, but excellent documentation for <code>ggplot2</code> can be found at the <a href="https://ggplot2-book.org/">ggplot2: Elegant Graphics for Data Analysis</a> website, written by the package authors.</p>
</div>
<div id="bar-graphs" class="section level2 hasAnchor" number="1.17">
<h2><span class="header-section-number">1.17</span> Bar graphs<a href="introduction-to-r-and-rstudio.html#bar-graphs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simplest way to use the <code>plot()</code> function is by specifying an object to be plotted. As with the <code>hist()</code> function, to plot a single variable from a data frame, we must define it using: <code>dataframe$variable</code>.</p>
<p>Here we will create the bar chart shown in Figure 1.3 of the statistics notes using the <code>pbc.rds</code> dataset. The x-axis of this graph will be the stage of disease, and the y-axis will show the number of participants in each category.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="introduction-to-r-and-rstudio.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pbc<span class="sc">$</span>stage, </span>
<span id="cb33-2"><a href="introduction-to-r-and-rstudio.html#cb33-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Bar graph of stage of disease from PBC study&quot;</span>, </span>
<span id="cb33-3"><a href="introduction-to-r-and-rstudio.html#cb33-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Number of participants&quot;</span>)</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>Note that stage is a categorical variable, that has been defined as a factor (in Section <a href="introduction-to-r-and-rstudio.html#defining-categorical-variables-as-factors">1.13.1</a>). You <strong>must define categorical data as factors</strong> to plot them in a bar graph.</p>
<div id="clustered-bar-graph" class="section level3 hasAnchor" number="1.17.1">
<h3><span class="header-section-number">1.17.1</span> Clustered bar graph<a href="introduction-to-r-and-rstudio.html#clustered-bar-graph" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To create a clustered bar chart as shown in Figure 1.4 of the statistics notes, we need to do a bit of manipulation. We first need to tabulate the data using the <code>table()</code> function. We want to plot stage of disease broken down by sex, so we specify <code>sex</code> as the first variable, and <code>stage</code> as the second variable for the <code>table()</code> command.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="introduction-to-r-and-rstudio.html#cb34-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">table</span>(pbc<span class="sc">$</span>sex, pbc<span class="sc">$</span>stage)</span>
<span id="cb34-2"><a href="introduction-to-r-and-rstudio.html#cb34-2" aria-hidden="true" tabindex="-1"></a>counts</span></code></pre></div>
<pre><code>##         
##          Stage 1 Stage 2 Stage 3 Stage 4
##   Male         3       8      16      17
##   Female      18      84     139     127</code></pre>
<p>After tabulating the data, we use the <code>barplot()</code> function to plot the summarised data. We specify the main title using <code>main=" "</code>, specify that the stages be plotted separately by sex (<code>beside=TRUE</code>), specify the legend be defined by sex, and position the legend in the top-left of the graph:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="introduction-to-r-and-rstudio.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(counts, <span class="at">main=</span><span class="st">&quot;Bar graph of stage of disease by sex from PBC study&quot;</span>,</span>
<span id="cb36-2"><a href="introduction-to-r-and-rstudio.html#cb36-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">beside=</span><span class="cn">TRUE</span>, <span class="at">legend =</span> <span class="fu">rownames</span>(counts), <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>))</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
</div>
<div id="stacked-bar-graph" class="section level3 hasAnchor" number="1.17.2">
<h3><span class="header-section-number">1.17.2</span> Stacked bar graph<a href="introduction-to-r-and-rstudio.html#stacked-bar-graph" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A stacked bar graph can be constructed as for the clustered bar graph, but we specify <code>beside=FALSE</code>:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="introduction-to-r-and-rstudio.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(counts, <span class="at">main=</span><span class="st">&quot;Bar graph of stage of disease by sex from PBC study&quot;</span>,</span>
<span id="cb37-2"><a href="introduction-to-r-and-rstudio.html#cb37-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">beside=</span><span class="cn">FALSE</span>, <span class="at">legend =</span> <span class="fu">rownames</span>(counts), <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>))</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
</div>
<div id="stacked-bar-graph-of-relative-frequencies" class="section level3 hasAnchor" number="1.17.3">
<h3><span class="header-section-number">1.17.3</span> Stacked bar graph of relative frequencies<a href="introduction-to-r-and-rstudio.html#stacked-bar-graph-of-relative-frequencies" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To plot relative frequencies, we need to transform our table of frequencies (<code>counts</code>) into proportions, by using the <code>prop.table()</code> function. The prop.table() function takes two arguments: a table of counts, and <code>margin</code>, which defines whether we want proportions calculated by row (<code>margin=1</code>) or column (<code>margin=2</code>).</p>
<p>We want to calculate the relative frequency of sex within each stage category. From our <code>counts</code> table above, this equates to calculating <em>column</em> proportions, so we specify <code>margin=2</code>. We also multiply the resulting table by 100 to obtain percentages (rather than proportions):</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="introduction-to-r-and-rstudio.html#cb38-1" aria-hidden="true" tabindex="-1"></a>percent <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(counts, <span class="at">margin=</span><span class="dv">2</span>)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb38-2"><a href="introduction-to-r-and-rstudio.html#cb38-2" aria-hidden="true" tabindex="-1"></a>percent</span></code></pre></div>
<pre><code>##         
##            Stage 1   Stage 2   Stage 3   Stage 4
##   Male   14.285714  8.695652 10.322581 11.805556
##   Female 85.714286 91.304348 89.677419 88.194444</code></pre>
<p>After calculating the percentages, we use <code>barplot()</code> again, similar to the stacked bar graph:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="introduction-to-r-and-rstudio.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(percent, </span>
<span id="cb40-2"><a href="introduction-to-r-and-rstudio.html#cb40-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Relative frequency of sex within stage of disease from PBC study&quot;</span>,</span>
<span id="cb40-3"><a href="introduction-to-r-and-rstudio.html#cb40-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend =</span> <span class="fu">rownames</span>(counts), <span class="at">beside=</span><span class="cn">FALSE</span>, <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">&quot;topright&quot;</span>))</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
</div>
</div>
<div id="creating-line-graphs" class="section level2 hasAnchor" number="1.18">
<h2><span class="header-section-number">1.18</span> Creating line graphs<a href="introduction-to-r-and-rstudio.html#creating-line-graphs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To demonstrate the graphing of aggregate data , we use the data on new cases and deaths from prostate cancer in males in NSW. This data has been entered as <code>Example_1.2.rds</code>.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="introduction-to-r-and-rstudio.html#cb41-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/examples/Example_1.2.rds&quot;</span>)</span>
<span id="cb41-2"><a href="introduction-to-r-and-rstudio.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cancer)</span></code></pre></div>
<pre><code>##       year          ncases        ndeaths           rcases         rdeaths     
##  Min.   :1987   Min.   :1567   Min.   : 645.0   Min.   : 81.8   Min.   :31.10  
##  1st Qu.:1992   1st Qu.:2804   1st Qu.: 788.2   1st Qu.:121.9   1st Qu.:34.67  
##  Median :1996   Median :3790   Median : 868.0   Median :131.3   Median :36.55  
##  Mean   :1996   Mean   :3719   Mean   : 855.0   Mean   :135.4   Mean   :37.09  
##  3rd Qu.:2001   3rd Qu.:4403   3rd Qu.: 921.0   3rd Qu.:164.2   3rd Qu.:40.38  
##  Max.   :2006   Max.   :6158   Max.   :1044.0   Max.   :186.9   Max.   :43.80</code></pre>
<p>We begin by plotting cancer cases (as the <em>y</em> variable) against year (the <em>x</em> variable).</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="introduction-to-r-and-rstudio.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>cancer<span class="sc">$</span>year, <span class="at">y=</span>cancer<span class="sc">$</span>rcases)</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Let’s define the plot to be joined by lines (<code>type="l"</code>), in the colour red (<code>col="red"</code>), providing meaningful labels for the x-axis and y-axis, and changing the scale of the y-axis to be between 0 and 200 (<code>ylim=c(0,200)</code>):</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="introduction-to-r-and-rstudio.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>cancer<span class="sc">$</span>year, <span class="at">y=</span>cancer<span class="sc">$</span>rcases, </span>
<span id="cb44-2"><a href="introduction-to-r-and-rstudio.html#cb44-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb44-3"><a href="introduction-to-r-and-rstudio.html#cb44-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Year&quot;</span>, </span>
<span id="cb44-4"><a href="introduction-to-r-and-rstudio.html#cb44-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Age-standardised rate (per 100,000)&quot;</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">200</span>))</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>We can now add a second line to the plot using the <code>lines()</code> function, specifying a dashed line (<code>lty=2</code>), and add a legend to the plot:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="introduction-to-r-and-rstudio.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>cancer<span class="sc">$</span>year, <span class="at">y=</span>cancer<span class="sc">$</span>rcases, <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb45-2"><a href="introduction-to-r-and-rstudio.html#cb45-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Age-standardised rate (per 100,000)&quot;</span>, </span>
<span id="cb45-3"><a href="introduction-to-r-and-rstudio.html#cb45-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">200</span>))</span>
<span id="cb45-4"><a href="introduction-to-r-and-rstudio.html#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="introduction-to-r-and-rstudio.html#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(cancer<span class="sc">$</span>year, cancer<span class="sc">$</span>rdeaths, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb45-6"><a href="introduction-to-r-and-rstudio.html#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="introduction-to-r-and-rstudio.html#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;Incidence&quot;</span>, <span class="st">&quot;Deaths&quot;</span>), </span>
<span id="cb45-8"><a href="introduction-to-r-and-rstudio.html#cb45-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="at">lty =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="phcm9795-R-notes_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>Note: coding for graphs is not always straightforward. Two excellent resources for creating graphs in R are: <a href="https://r-graphics.org/">R Graphics Cookbook</a> and <a href="https://r-graph-gallery.com/">The R Graph Gallery</a>.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-therneau_grambsch10" class="csl-entry">
Therneau, Terry M., and Patricia M. Grambsch. 2010. <em>Modeling <span>Survival Data</span>: <span>Extending</span> the <span>Cox Model</span></em>. <span>New York Berlin Heidelberg</span>: <span>Springer</span>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>these R notes and the PHCM9795 course notes have been written using <a href="https://bookdown.org/yihui/bookdown/">bookdown</a><a href="introduction-to-r-and-rstudio.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability-and-probability-distributions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["phcm9795-R-notes.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
